Forums/Models/Search/SearchResultModel.cs
using Forums.Models.Post;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Forums.Models.Search
{
    public class SearchResultModel
    {
        public IEnumerable<PostListingModel> Posts { get; set; }
        public string SearchQuery { get; set; }
        public bool EmptySearchResults { get; set; }
    }
}

Forums/Controllers/ForumController.cs
using System.Collections.Generic;
using System.Linq;
using Forums.Data;
using Forums.Data.Models;
using Forums.Models.Forum;
using Forums.Models.Post;
using Microsoft.AspNetCore.Mvc;

namespace Forums.Controllers
{
    public class ForumController : Controller
    {
        private readonly IForum _forumService;
        private readonly IPost _postService;

        public ForumController(IForum forumService, IPost postService)
        {
            _forumService = forumService;
            _postService = postService;
        }

        public IActionResult Index()
        {
            var forums = _forumService.GetAll()
                .Select(forum => new ForumListingModel {
                    Id = forum.Id,
                    Name = forum.Title,
                    Description = forum.Description
                });

            var model = new ForumIndexModel
            {
                ForumList = forums
            };

            return View(model);
        }

        public IActionResult Topic(int id, string searchQuery)
        {
            var forum = _forumService.GetById(id);
            var posts = new List<Post>();
            
            posts = _postService.GetFilteredPosts(forum, searchQuery).ToList();

            var postListings = posts.Select(post => new PostListingModel
            {
                Id = post.Id,
                AuthorId = post.User.Id,
                AuthorRating = post.User.Rating,
                AuthorName = post.User.UserName,
                Title = post.Title,
                DatePosted = post.Created.ToString(),
                RepliesCount = post.Replies.Count(),
                Forum = BuildForumListing(post)
            });

            var model = new ForumTopicModel
            {
                Posts = postListings,
                Forum = BuildForumListing(forum)
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult Search(int id, string searchQuery)
        {
            return RedirectToAction("Topic", new { id, searchQuery });
        }

        private ForumListingModel BuildForumListing(Post post)
        {
            var forum = post.Forum;
            return BuildForumListing(forum);
        }

        private ForumListingModel BuildForumListing(Forum forum)
        {
            return new ForumListingModel
            {
                Id = forum.Id,
                Name = forum.Title,
                Description = forum.Description,
                ImageUrl = forum.ImageUrl
            };
        }
    }
}

Forums/Controllers/SearchController.cs
using Forums.Data;
using Forums.Data.Models;
using Forums.Models.Forum;
using Forums.Models.Post;
using Forums.Models.Search;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Forums.Controllers
{
    public class SearchController : Controller
    {
        private readonly IPost _postService;

        public SearchController(IPost postService)
        {
            _postService = postService;
        }

        public IActionResult Results(string searchQuery)
        {
            var posts = _postService.GetFilteredPosts(searchQuery);
            var areNoResults = (!string.IsNullOrEmpty(searchQuery) && !posts.Any());

            var postListings = posts.Select(post => new PostListingModel
            {
                Id = post.Id,
                AuthorId = post.User.Id,
                AuthorName = post.User.UserName,
                AuthorRating = post.User.Rating,
                Title = post.Title,
                DatePosted = post.Created.ToString(),
                RepliesCount = post.Replies.Count(),
                Forum = BuildForumListing(post)
            });

            var model = new SearchResultModel
            {
                Posts = postListings,
                SearchQuery = searchQuery,
                EmptySearchResults = areNoResults
            };

            return View(model);
        }

        private ForumListingModel BuildForumListing(Post post)
        {
            var forum = post.Forum;

            return new ForumListingModel
            {
                Id = forum.Id,
                ImageUrl = forum.ImageUrl,
                Name = forum.Title,
                Description = forum.Description
            };
        }

        [HttpPost]
        public IActionResult Search(string searchQuery)
        {
            return RedirectToAction("Results", new { searchQuery });
        }
    }
}

Forums/Views/Search/Results.cshtml
@model Forums.Models.Search.SearchResultModel

<div class="container body-content">
    <div class="row sectionHeader">
        <div class="sectionHeading">
            <span id="results">Search Results for: @Model.SearchQuery</span>
            <form asp-controller="Search" asp-action="Search" method="post">
                <div class="searchForm">
                    <input asp-for="SearchQuery" type="text" placeholder="Search..." class="searchBar" onfocus="clearThis(this)">
                    <button type="submit" class="btn btn-forumSearch">
                        <i class="material-icons">search</i>
                    </button>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        @if (!Model.EmptySearchResults)
        {
            <table class="table table-hover table-bordered" id="searchIndexTable">
                <tbody>
                    @foreach (var post in Model.Posts)
                    {
                        <tr>
                            <td>
                                <div class="forumLogo" style="background-image: url(@post.Forum.ImageUrl"></div>
                                <div class="postData">
                                    <div class="postTitle">
                                        <a asp-controller="Post" asp-action="Index" asp-route-id="@post.Id">@post.Title</a>
                                    </div>
                                    <div class="forumSubTitle">
                                        <div>
                                            by:
                                            <span class="postAuthor">
                                                <a asp-controller="Profile" asp-action="Detail" asp-route-id="@post.AuthorId">
                                                    @post.AuthorName
                                                </a>
                                                (@post.AuthorRating)
                                            </span>
                                            in:
                                            <span class="postForum">
                                                <a asp-controller="Forum" asp-action="Topic" asp-route-id="@post.Forum.Id">@post.Forum.Name</a>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <div class="forumPostCount">
                                    Replies: @post.RepliesCount
                                </div>
                            </td>
                            <td>
                                <div class="postDate">@post.DatePosted</div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <div class="noPosts">
                <i class="material-icons md-72">question_answer</i>
                <h3>
                    No search results found for @Model.SearchQuery <br />
                </h3>
            </div>
        }
    </div>
</div>

@section Scripts {
    <script>
        function clearThis(target) {
            target.value = "";
        }
    </script>
}